config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  get "lessons" => "lessons#index"

  namespace :admin do
    resources :categories
    resources :words
  end
  resources :users
  resources :relationships, only: [:index, :create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories do
    resources :lessons
  end
  resources :results
  resources :words, only: [:index]
end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :category
  has_many :answers, dependent: :destroy
  has_many :results
  has_many :lessons, through: :results
  validates :content, presence: true, length: {maximum: 50}
  validate :checked_answer, on: [:create, :update]
  before_save :update_updated_at_field
  accepts_nested_attributes_for :answers, allow_destroy: true
  scope :by_category, ->(category_id) do
    condition = category_id.blank? ? nil : "words.category_id = #{category_id}"
    where(condition).order updated_at: :desc
  end
  scope :by_user_id, -> id do
    where(users: {id: id})
  end
  scope :learned, ->(user) do
    joins(results: {lesson: :user}).by_user_id(user.id).distinct
  end
  scope :remembered, ->(user) do
    joins(results: [{lesson: :user}, :answer])
      .by_user_id(user.id).where(answers: {is_true: true}).distinct
  end
  scope :not_remembered, ->(user) do
    joins(results: [{lesson: :user}, :answer])
      .by_user_id(user.id).where(answers: {is_true: false}).distinct
  end
  scope :not_learned, ->(user) do
    where.not(id: joins(results: {lesson: :user}).by_user_id(user.id)).distinct
  end
  scope :unfinished, ->(user) do
    joins(results: {lesson: :user}).by_user_id(user.id).where(results: {answer_id: nil}).distinct
  end

  def invalid_to_delete?
    self.lessons.any?
  end

  scope :unlearned, -> do
    where :category_id => Category.joins(:lessons, :words)
      .where.not(lessons: {is_finished: true}).distinct
  end

  scope :randomize, ->(word_per_page) do
    order("RANDOM()").limit(word_per_page)
  end

  def correct_answer
    answer = self.answers.detect {|answer| answer.is_true?}
    answer.content
  end

  private
  def checked_answer
    has_answer = self.answers.detect {|answer| answer.is_true?}
    errors[:base] << I18n.t("model.word.select-an-answer") if has_answer.nil?
  end

  def update_updated_at_field
    self.updated_at = Time.zone.now
  end
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  before_action :require_logged_in_user, :require_logged_in_as_admin
  before_action :load_word, only: [:edit, :update, :destroy]
  before_action :load_categories, except: [:destroy]

  def index
    @words = Word.by_category(params[:category_id])

    page = params[:page].to_i
    unless @words.size > (Settings.word_per_page * (page - 1))
      page -= 1
    end
    page = 1 if page <= 0

    @words = @words.paginate(page: page.to_i).
      per_page Settings.word_per_page
  end

  def new
    @word = Word.new
    Settings.answers_num_default.times {@word.answers.build}
  end

  def create
    @word = Word.new word_params
    if @word.save
      flash[:success] = t ".success"
      redirect_to admin_words_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @word.update_attributes word_params
      flash[:success] = t ".success"
      redirect_to admin_words_path
    else
      render :edit
    end
  end

  def destroy
    if @word.invalid_to_delete?
      flash[:danger] = t ".fail"
    else
      @word.destroy
      flash[:success] = t ".success"
    end
    redirect_to admin_words_path category_id: params[:category_id],
      page: params[:page]
  end

  private
  def load_word
    @word = Word.find_by id: params[:id]
    unless @word
      flash[:danger] = t "not-exist-page"
      redirect_to admin_words_path
    end
  end

  def load_categories
    @categories = Category.alphabet
  end

  def word_params
    params.require(:word).permit :content, :category_id,
      answers_attributes: [:id, :content, :is_true, :_destroy]
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :require_logged_in_user, :load_filter_list, only: [:index]

  def index
    @categories = Category.all

    params[:filter_by] = :all.to_s if params[:filter_by].blank?

    @words = params[:filter_by] == :all.to_s ? Word.all :
      Word.send("#{params[:filter_by]}", current_user)

    @words = @words.by_category(params[:category_id])
      .paginate(page: params[:page])
      .per_page Settings.word_per_page
  end

  private
  def load_filter_list
    @list_filter = {}
    @list_filter[:learned] = t ".learned"
    @list_filter[:remembered] = t ".remember"
    @list_filter[:not_remembered] = t ".not-remember"
    @list_filter[:not_learned] = t ".notlearned"
    @list_filter[:unfinished] = t ".unfinished"
    @list_filter[:all] = t ".all"
  end
end

app/helpers/words_helper.rb
module WordsHelper
  def link_to_add_fields name, f, association
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |form|
      render(association.to_s.singularize + "_fields", f: form)
    end
    link_to name, "", class: "add_fields btn btn-info active pull-right",
      data: {id: id, fields: fields.gsub("\n", "")}
  end

  def disable_select_category? action
    action == :edit.to_s
  end
end

app/views/admin/words/_answer_fields.html.erb
<div class="input-group">
  <span class="input-group-addon">
    <%= f.radio_button :is_true, :true, {checked: f.object.is_true, class: "answer-option"} %>
    <%= f.hidden_field :is_true, class: "hidden_for_answer" %>
  </span>
  <%= f.text_field :content, class:"form-control" %>
  <%= f.hidden_field :_destroy %>
  <span class="input-group-addon">
    <%= link_to t("remove"), "#", class: "remove_fields pull-right" %>
  </span>
</div>

app/views/admin/words/_filter_form.html.erb
<div id="filter-form" class="text-center">
  <%= form_tag admin_words_path, method: :get, class: "form-inline" do %>
    <%= label_tag "#", t("admin.categories.name-singular") %>
    <%= select_tag :category_id,
      options_from_collection_for_select(@categories, :id, :name,
      params[:category_id]),
      {include_blank: t("all"), class: "form-control"} %>
    <%= submit_tag t("filter"), class: "form-control" %>
  <% end %>
</div>

app/views/admin/words/_form.html.erb
<div id="word-form-container" class="row">
  <%= form_for [:admin, @word] do |f| %>
    <div class="col-md-6 col-md-offset-3 form-group">
      <%= render "shared/error_messages", object: f.object %>
    </div>
    <div class="col-md-6 col-md-offset-3 form-group">
      <%= f.label :category %><br>
      <%= f.collection_select :category_id, @categories, :id, :name, {},
        {class: "form-control",
        disabled: disable_select_category?(params[:action])} %>
    </div>
    <div class="col-md-6 col-md-offset-3 form-group">
      <%= f.label :content %><br>
      <%= f.text_field :content, class: "form-control" %>
    </div>
    <div class="col-md-6 col-md-offset-3 form-group">
      <label><%= t ".answers" %></label>
      <%= link_to_add_fields "Add answers", f, :answers %>
    </div>
    <div id="answers-block" class="col-md-6 col-md-offset-3 form-group">
      <%= f.fields_for :answers do |answers_for_form| %>
        <%= render "answer_fields", f: answers_for_form %>
      <% end %>
    </div>
    <div class="col-md-6 col-md-offset-3 form-group text-center">
      <%= f.submit yield(:button_text), class: "btn btn-primary text-center" %>
    </div>
  <% end %>
  <%= hidden_field_tag "at-least-two-answers-msg", t("required-two-answers") %>
  <%= hidden_field_tag "cannot-remove-correct-ans", t("warning-remove-correct-ans") %>
</div>

app/views/admin/words/_word.html.erb
<div class="word">
  <span class="word-question"><%= word.content %></span>
  <span class="word-answer"><%= word.correct_answer %></span>
  <div class="word-action">
    <div class="edit-btn">
      <%= link_to t("edit"), edit_admin_word_path(word),
        class: "btn btn-primary" %>
    </div>
    <%= link_to t("delete"), admin_word_path(word,
      category_id: params[:category_id], page: params[:page]), method: :delete,
      data: {confirm: t("confirm")}, class: "btn btn-danger" %>
  </div>
</div>

app/views/admin/words/edit.html.erb
<% provide :button_text, t("edit") %>
<div class="main-container">
  <h1 class="text-center "><%= t ".edit-word" %></h1>
  <%= render "form" %>
</div>

app/views/admin/words/index.html.erb
<div class="main-container">
  <div class="form-inline">
    <h1 class="text-center "><%= t ".word-list" %></h1>
  </div>
  <div class="search-form">
    <%= render "filter_form" %>
  </div>
  <div id="new-word">
    <a href="<%= new_admin_word_path %>" class="pull-right">
      <button class="btn btn-primary"><%= t ".add-new" %></button>
    </a>
  </div>
  <div id="words-section">
    <% if @words.any? %>
      <div id="words-container">
        <%= render @words %>
      </div>
      <div class="pagination-container text-center">
        <%= will_paginate @words %>
      </div>
    <% else %>
      <h2><%= t ".no-record-found" %></h2>
    <% end %>
  </div>
</div>

app/views/admin/words/new.html.erb
<% provide :button_text, t("create") %>
<div class="main-container">
  <h1 class="text-center "><%= t ".new-word" %></h1>
  <%= render "form" %>
</div>