config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  get "lessons" => "lessons#index"

  namespace :admin do
    resources :categories
    resources :words
  end
  resources :users
  resources :relationships, only: [:index, :create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories do
    resources :lessons
  end
  resources :results
  resources :words, only: [:index]
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  before_save {email.downcase!}
  has_many :lessons, dependent: :destroy
  has_many :activities, dependent: :destroy
  has_many :active_relationships, class_name: Relationship.name,
    foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 100},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}
  validates :fullname, presence: true, length: {maximum: 50}
  validates :password, length: {minimum: 6}
  has_secure_password

  class << self
    def digest string
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
      BCrypt::Password.create string, cost: cost
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def follow user
    active_relationships.create followed_id: user.id
  end

  def unfollow user
    active_relationships.find_by(followed_id: user.id).destroy
  end

  def following? user
    following.include? user
  end

  def is? user
    self == user
  end

  def remember
    self.remember_token = User.new_token
    update_attributes remember_digest: User.digest(remember_token)
  end

  def authenticated? remember_token
    BCrypt::Password.new remember_digest == remember_token
  end

  def forget
    update_attributes remember_digest: nil
  end

  def is_user? user
    self == user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_in_user, except: [:new, :create]
  before_action :correct_user, only: [:edit, :update]
  before_action :load_user, except: [:index, :new, :create]
  before_action :require_logged_in_as_admin, only: :destroy

  def index
    @users = User.paginate page: params[:page]
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      flash[:success] = t "Success_sign_up"
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = t "update_success"
      redirect_to root_url
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    flash[:success] = t "destroy_success"
    redirect_to users_url
  end

  private
  def user_params
    params.require(:user).permit :fullname, :email, :password,
      :password_confirmation, :gender
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user
    gravatar_id = Digest::MD5::hexdigest user.email.downcase
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag gravatar_url, alt: user.fullname, class: "gravatar"
  end

  def display_activity activity
  	unless (["follow", "unfollow"].include?(activity.action_type)) && (User.find_by(id: activity.target_id).nil?)
  	  render "/users/activity", activity:activity
  	end
  end
end

app/views/users/_activity.html.erb
<li>
  <p class="timeline-date"></p>
    <div class="timeline-content">
    <h3></h3>
  <p><%= activity.load_activity %></p>
</li>

app/views/users/_follow.html.erb
<%= form_for current_user.active_relationships.build, remote: true do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit t("follow"), class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user.is? @user %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render "unfollow" %>
    <% else %>
      <%= render "follow" %>
    <% end %>
  </div>
<% end %>

app/views/users/_show_follow.html.erb
<div id="follow-users">
  <%= render users %>
</div>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <%= link_to "#{@user.following.count} Followers",
    relationships_path(id: @user.id, type: :following),
    remote: :true, id: "following" %>
  <%= link_to "#{@user.followers.count} Followers",
    relationships_path(id: @user.id, type: :followers),
    remote: :true, id: "followers" %>
</div>

app/views/users/_unfollow.html.erb
<%= form_for current_user.active_relationships.find_by(followed_id: @user.id),
             html: {method: :delete}, remote: true do |f| %>
  <%= f.submit t("unfollow"), class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user%>
  <%= link_to user.fullname, user %>
  <% if current_user.is_admin? && !current_user.is?(user) %>
    | <%= link_to t("delete"), user, method: "delete", data: {confirm: "You sure?"} %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide :title, t("sign_up") %>
<div id="content">
  <div class="whereheader">
    <%= link_to t("edit_profile"), "#", class: "large" %>
  </div>
  <div id="signupform">
    <%= form_for @user do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <div class="form-sign">
        <div class="gravatar_edit">
          <%= gravatar_for @user %>
          <%= link_to t("change_img"), "http://gravatar.com/emails",
            targets: "_blank" %>
        </div>

        <%= f.text_field :fullname, placeholder: t("full_name_placeholder") %>
        <%= f.email_field :email, placeholder: t("email_placeholder") %>
        <%= f.password_field :password,
          placeholder: t("password_placeholder") %>
        <%= f.password_field :password_confirmation,
          placeholder: t("password_confirmation_placeholder") %>
        <div class="gender">
          <%= f.select :gender, [[t("male"), true], [t("female"), false]] %>
        </div>
        <%= f.submit t("save_change") %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide :title, t("index_user") %>
<div id="content">
  <div class="whereheader">
    <%= link_to t("index_user"), root_path, class: "large" %>
  </div>
  <div id="signupform">
    <ul class="users">
      <%= render @users %>
    </ul>
    <%= will_paginate %>
  </div>
</div>

app/views/users/new.html.erb
<% provide :title, t("sign_up") %>
<div id="content">
  <div id="signupform">
    <%= form_for @user do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <div class="form-sign">
        <h2><%= t "sign_up" %></h2>
        <%= f.text_field :fullname, placeholder: t("full_name_placeholder") %>
        <%= f.email_field :email, placeholder: t("email_placeholder") %>
        <%= f.password_field :password,
          placeholder: t("password_placeholder") %>
        <%= f.password_field :password_confirmation,
          placeholder: t("password_confirmation_placeholder") %>
        <div class="gender">
          <%= f.select :gender, [[t("male"), true], [t("female"), false]] %>
        </div>
        <%= f.submit t("sign_up") %>
        <div class="remind">
          <span>
            <%= t "remind_sign_up" %>
            <%= link_to t("sign_in"), new_session_path %>
          </span>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.fullname %>
<div id="content">
  <div class="whereheader">
    <% if logged_in? %>
      <%= link_to t("activity"),
        @user, class: "large" %>
    <% else %>
      <%= link_to "#{t("profile_of")} #{@user.fullname}",
        @user, class: "large" %>
    <% end %>
  </div>
  <div id="profileform">
    <div class="left_form">
      <div class="gravatar_edit">
        <%= gravatar_for @user %>
      </div>
      <div class="information">
        <h1><%= label_tag "name", @user.fullname, class: "name" %><h1>
        <h3><%= label_tag "name", @user.email, class: "email" %></h3>
      </div>
      <div class="follower_followed text-center">
        <%= render "stats" %>
        <% unless current_user.is? @user %>
          <%= render "follow_form" %>
        <% end %>
      </div>
    </div>
    <div class="right_form" id="activities-body">
      <ul class="timeline">
      <% @user.activities.each do |activity| %>
        <%= display_activity activity %>
      <% end %>
    </ul>
    </div>
  </div>
  <div id="clearfix">This is hidden</div>
</div>