config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  get "lessons" => "lessons#index"

  namespace :admin do
    resources :categories
    resources :words
  end
  resources :users
  resources :relationships, only: [:index, :create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories do
    resources :lessons
  end
  resources :results
  resources :words, only: [:index]
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :words
  has_many :lessons
  scope :update_desc, -> {order(updated_at: :desc)}
  scope :alphabet, -> {order(:name)}
  validates :name, presence: true, length: {maximum: 140}

  def valid_to_delete?
    self.words.any?
  end

  class << self
    def search search
      where("name LIKE ?", "%#{search}%").update_desc
    end
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :require_logged_in_user, :require_logged_in_as_admin
  before_action :load_category, only: [:edit, :update, :destroy]

  def index
    if params[:search]
      @categories = Category.search params[:search]
    else
      @categories = Category.update_desc
    end

    page = params[:page].to_i
    unless @categories.size > (Settings.page_size * (page - 1))
      page -= 1
    end
    page = 1 if page <= 0

    @categories = @categories.paginate(page: page.to_s)
      .per_page Settings.page_size
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t ".success"
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t ".success"
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def destroy
    if @category.valid_to_delete?
      flash[:danger] = t ".fail"
    else
      @category.destroy
      flash[:success] = t ".success"
    end
    redirect_to admin_categories_path(search: params[:search],
      page: params[:page])
  end

  private
  def load_category
    @category = Category.find_by id: params[:id]
    unless @category
      flash[:danger] = t "not-exist-page"
      redirect_to admin_categories_path
    end
  end

  def category_params
    params.require(:category).permit :name, :description
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_logged_in_user
  def index
    @categories = Category.paginate(page: params[:page])
      .per_page Settings.page_size
  end
end

app/views/admin/categories/_category.html.erb
<tr>
  <td><%= category.name %></td>
  <td><%= category.description %></td>
  <td><%= link_to t("edit"), edit_admin_category_path(category) %></td>
  <td><%= link_to t("delete"), admin_category_path(category,
    search: params[:search], page: params[:page]), method: :delete,
    data: {confirm: t("confirm")} %></td>
</tr>

app/views/admin/categories/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @category] do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <div class="form-group">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :description %><br>
        <%= f.text_area :description, class: "form-control resize-vertical" %>
      </div>
      <div class="form-group text-center">
        <%= f.submit yield(:button_text), class: "btn btn-primary text-center" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/categories/_search_form.html.erb
<div id="search-form">
  <%= form_tag admin_categories_path, method: "get", class: "form-inline" do %>
    <%= text_field_tag :search, params[:search], class: "form-control" %>
    <%= submit_tag t("search"), class: "form-control" %>
  <% end %>
</div>

app/views/admin/categories/edit.html.erb
<% provide :button_text, t("edit") %>
<div class="main-container">
  <h1 class="text-center "><%= t ".edit-category" %></h1>
  <%= render "form" %>
</div>

app/views/admin/categories/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="top-navigation">
    <span class="form-inline ">
      <span class="header-text"><%= t "admin.categories.name-plural" %></span>
      <a href="<%= new_admin_category_path %>" class="button-right">
        <button class="btn btn-primary"><%= t ".add-new" %></button>
      </a>
    </span>
  </div>
  <div class="search-form">
    <%= render "search_form" %>
  </div>
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th class="header-table"><%= t "admin.categories.name-header" %></th>
        <th class="header-table"><%= t "admin.categories.description-header" %></th>
        <th class="header-table" colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% if @categories.any? %>
        <%= render @categories %>
        <%= will_paginate @categories %>
      <% else %>
        <tr>
          <td colspan="5"><%= t ".no-record-found" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
</div>

app/views/admin/categories/new.html.erb
<% provide :button_text, t("create") %>
<div class="main-container">
  <h1 class="text-center "><%= t ".new-category" %></h1>
  <%= render "form" %>
</div>